#ifndef HTMLS_H
#define HTMLS_H
#include <string>
 std::string login =
"<!DOCTYPE html>"
"<html>"
"<head><title>Login</title></head>"
"<body>"
"<h2>Login</h2>"
"<input id='u' placeholder='User ID'><br><br>"
"<input id='p' type='password' placeholder='Password'><br><br>"
"<button onclick='login()'>Login</button>"
"<button onclick='goSignup()'>Sign Up</button>"
"<p id='msg' style='color:red;'></p>"
"<script>"
"function login(){"
"const uid=document.getElementById('u').value;"
"const pass=document.getElementById('p').value;"
"fetch('/login',{"
"method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({uid:uid,pass:pass})"
"})"
".then(r=>r.text())"
".then(data=>{"
"if(data==='ok'){"
"window.location.href='/home';"
"}else{"
"document.getElementById('msg').innerText='Invalid credentials';"
"}"
"});"
"}"
"function goSignup(){"
"window.location.href='/signup';"
"}"
"</script>"
"</body></html>";



std::string home =
"<!DOCTYPE html>"
"<html><body>"
"<h2>Welcome</h2>"
"<div style='display:flex;'>"
"<div style='width:30%;border-right:1px solid black;'>"
"<h3>Friends</h3>"
"<ul id='friends'></ul>"
"</div>"
"<div style='width:70%;padding-left:10px;'>"
"<h3>Messages</h3>"
"<div id='chat' style='height:200px;overflow:auto;border:1px solid black;'></div><br>"
"<input id='to' placeholder='To'><br>"
"<input id='msg' placeholder='Message'><br>"
"<button onclick='sendMsg()'>Send</button>"
"</div>"
"</div>"
"<script>"
"function loadFriends(){"
"fetch('/friends')"
".then(r=>r.text())"
".then(data=>{"
"let arr = data.split('\\n');"
"let list='';"
"arr.forEach(f=>{ if(f) list += '<li>'+f+'</li>'; });"
"document.getElementById('friends').innerHTML = list;"
"});"
"}"
"function loadMessages(){"
"fetch('/get')"
".then(r=>r.text())"
".then(data=>{"
"if(data){"
"document.getElementById('chat').innerHTML += data + '<br>';"
"}"
"});"
"}"
"function sendMsg(){"
"const to=document.getElementById('to').value;"
"const msg=document.getElementById('msg').value;"
"fetch('/home',{"
"method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({uid:to,pass:msg})"
"});"
"}"
"setInterval(loadMessages,200);"
"setInterval(loadFriends,500);"
"loadFriends();"
"loadMessages();"
"</script>"
"</body></html>";


std::string sign =
"<!DOCTYPE html>"
"<html>"
"<head><title>Sign Up</title></head>"
"<body>"
"<h2>Sign Up</h2>"
"<input id='u' placeholder='New User ID'><br><br>"
"<input id='p' type='password' placeholder='New Password'><br><br>"
"<button onclick='signup()'>Save</button>"
"<p id='msg' style='color:green;'></p>"
"<script>"
"function signup(){"
"const uid=document.getElementById('u').value;"
"const pass=document.getElementById('p').value;"
"fetch('/signup',{"
"method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({uid:uid,pass:pass})"
"})"
".then(r=>r.text())"
".then(data=>{"
"document.getElementById('msg').innerText=data;"
"if(data==='ok'){"
"window.location.href='/';"
"}else{"
"document.getElementById('msg').innerText='Invalid credentials';"
"}"
"});"
"}"
"</script>"
"</body></html>";
#endif